spring:
    datasource:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/XEPDB1
        username: hr
        password: hr

mybatis: # ← spring: の外に出す！
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.example.hrapp.model

server:
    port: 8080
    servlet:
        context-path: /api
